### Configure a variable for the web service base address.
@base_address = https://localhost:5151/api/customers/

### Get customers in USA in XML format
GET https://localhost:5151/weatherforecast
Accept: application/xml